# version: "3.9"

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: tu_bd
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   backend:
#     build: .
#     container_name: spring_backend
#     restart: always
#     depends_on:
#       - mysql
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tu_bd
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: root

# volumes:
#   mysql_data:
